query Repository(
  $owner: String!
  $name: String!
  $provider: RepositoryProvider
) {
  user {
    id
  }
  repositoryOverview(owner: $owner, name: $name, provider: $provider) {
    ... on Repository {
      id
    }
    ... on AvailableRepository {
      id
    }
  }
}
